/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.globalsight.ling.docproc.extractor.java;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int CRIPPLED_SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int ABSTRACT = 5;
  /** RegularExpression Id. */
  int BOOLEAN = 6;
  /** RegularExpression Id. */
  int BREAK = 7;
  /** RegularExpression Id. */
  int BYTE = 8;
  /** RegularExpression Id. */
  int CASE = 9;
  /** RegularExpression Id. */
  int CATCH = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int CONST = 13;
  /** RegularExpression Id. */
  int CONTINUE = 14;
  /** RegularExpression Id. */
  int _DEFAULT = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int DOUBLE = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int EXTENDS = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int FINAL = 21;
  /** RegularExpression Id. */
  int FINALLY = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int GOTO = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int IMPLEMENTS = 27;
  /** RegularExpression Id. */
  int IMPORT = 28;
  /** RegularExpression Id. */
  int INSTANCEOF = 29;
  /** RegularExpression Id. */
  int INT = 30;
  /** RegularExpression Id. */
  int INTERFACE = 31;
  /** RegularExpression Id. */
  int LONG = 32;
  /** RegularExpression Id. */
  int NATIVE = 33;
  /** RegularExpression Id. */
  int NEW = 34;
  /** RegularExpression Id. */
  int NULL = 35;
  /** RegularExpression Id. */
  int PACKAGE = 36;
  /** RegularExpression Id. */
  int PRIVATE = 37;
  /** RegularExpression Id. */
  int PROTECTED = 38;
  /** RegularExpression Id. */
  int PUBLIC = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int SHORT = 41;
  /** RegularExpression Id. */
  int STATIC = 42;
  /** RegularExpression Id. */
  int SUPER = 43;
  /** RegularExpression Id. */
  int SWITCH = 44;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 45;
  /** RegularExpression Id. */
  int THIS = 46;
  /** RegularExpression Id. */
  int THROW = 47;
  /** RegularExpression Id. */
  int THROWS = 48;
  /** RegularExpression Id. */
  int TRANSIENT = 49;
  /** RegularExpression Id. */
  int TRUE = 50;
  /** RegularExpression Id. */
  int TRY = 51;
  /** RegularExpression Id. */
  int VOID = 52;
  /** RegularExpression Id. */
  int VOLATILE = 53;
  /** RegularExpression Id. */
  int WHILE = 54;
  /** RegularExpression Id. */
  int STRICTFP = 55;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 56;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 57;
  /** RegularExpression Id. */
  int HEX_LITERAL = 58;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 59;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 60;
  /** RegularExpression Id. */
  int EXPONENT = 61;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 62;
  /** RegularExpression Id. */
  int STRING_LITERAL = 63;
  /** RegularExpression Id. */
  int IDENTIFIER = 64;
  /** RegularExpression Id. */
  int LETTER = 65;
  /** RegularExpression Id. */
  int DIGIT = 66;
  /** RegularExpression Id. */
  int LPAREN = 67;
  /** RegularExpression Id. */
  int RPAREN = 68;
  /** RegularExpression Id. */
  int LBRACE = 69;
  /** RegularExpression Id. */
  int RBRACE = 70;
  /** RegularExpression Id. */
  int LBRACKET = 71;
  /** RegularExpression Id. */
  int RBRACKET = 72;
  /** RegularExpression Id. */
  int SEMICOLON = 73;
  /** RegularExpression Id. */
  int COMMA = 74;
  /** RegularExpression Id. */
  int DOT = 75;
  /** RegularExpression Id. */
  int ASSIGN = 76;
  /** RegularExpression Id. */
  int GT = 77;
  /** RegularExpression Id. */
  int LT = 78;
  /** RegularExpression Id. */
  int BANG = 79;
  /** RegularExpression Id. */
  int TILDE = 80;
  /** RegularExpression Id. */
  int HOOK = 81;
  /** RegularExpression Id. */
  int COLON = 82;
  /** RegularExpression Id. */
  int EQ = 83;
  /** RegularExpression Id. */
  int LE = 84;
  /** RegularExpression Id. */
  int GE = 85;
  /** RegularExpression Id. */
  int NE = 86;
  /** RegularExpression Id. */
  int SC_OR = 87;
  /** RegularExpression Id. */
  int SC_AND = 88;
  /** RegularExpression Id. */
  int INCR = 89;
  /** RegularExpression Id. */
  int DECR = 90;
  /** RegularExpression Id. */
  int PLUS = 91;
  /** RegularExpression Id. */
  int MINUS = 92;
  /** RegularExpression Id. */
  int STAR = 93;
  /** RegularExpression Id. */
  int SLASH = 94;
  /** RegularExpression Id. */
  int BIT_AND = 95;
  /** RegularExpression Id. */
  int BIT_OR = 96;
  /** RegularExpression Id. */
  int XOR = 97;
  /** RegularExpression Id. */
  int REM = 98;
  /** RegularExpression Id. */
  int LSHIFT = 99;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 100;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 101;
  /** RegularExpression Id. */
  int PLUSASSIGN = 102;
  /** RegularExpression Id. */
  int MINUSASSIGN = 103;
  /** RegularExpression Id. */
  int STARASSIGN = 104;
  /** RegularExpression Id. */
  int SLASHASSIGN = 105;
  /** RegularExpression Id. */
  int ANDASSIGN = 106;
  /** RegularExpression Id. */
  int ORASSIGN = 107;
  /** RegularExpression Id. */
  int XORASSIGN = 108;
  /** RegularExpression Id. */
  int REMASSIGN = 109;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 110;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 111;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 112;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "<SINGLE_LINE_COMMENT>",
    "<CRIPPLED_SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"strictfp\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
