/* Generated By:JavaCC: Do not edit this line. AmbassadorDwUpParserConstants.java */
package com.globalsight.ling.tw.offline.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AmbassadorDwUpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START = 1;
  /** RegularExpression Id. */
  int NEWLINE = 2;
  /** RegularExpression Id. */
  int WHITESPACE = 3;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 4;
  /** RegularExpression Id. */
  int BOM = 5;
  /** RegularExpression Id. */
  int HEADER_HELP_LINE = 6;
  /** RegularExpression Id. */
  int HEADER_NOTE_LINE = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int SUBFLOW_ID = 9;
  /** RegularExpression Id. */
  int PAGE_NAME = 10;
  /** RegularExpression Id. */
  int SEG_FORMAT = 11;
  /** RegularExpression Id. */
  int MATCH_TYPE = 12;
  /** RegularExpression Id. */
  int MATCH_SCORE = 13;
  /** RegularExpression Id. */
  int RESOURCES = 14;
  /** RegularExpression Id. */
  int SOURCE_KEY = 15;
  /** RegularExpression Id. */
  int TARGET_KEY = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int END_LINE = 19;
  /** RegularExpression Id. */
  int TEXT = 20;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int START_LINE = 1;
  /** Lexical state. */
  int SEGMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<START>",
    "<NEWLINE>",
    "<WHITESPACE>",
    "<ALPHANUMERIC>",
    "<BOM>",
    "<HEADER_HELP_LINE>",
    "<HEADER_NOTE_LINE>",
    "<ID>",
    "<SUBFLOW_ID>",
    "<PAGE_NAME>",
    "<SEG_FORMAT>",
    "<MATCH_TYPE>",
    "<MATCH_SCORE>",
    "<RESOURCES>",
    "<SOURCE_KEY>",
    "<TARGET_KEY>",
    "\"# END GlobalSight Download File\"",
    "<token of kind 18>",
    "<END_LINE>",
    "<TEXT>",
    "\"# Encoding: \"",
    "\"# Document Format: \"",
    "\"# Placeholder Format: \"",
    "\"# Source Locale: \"",
    "\"# Target Locale: \"",
    "\"# Job ID: \"",
    "\"# Job Name: \"",
    "\"# Page Name: \"",
    "\"# Page ID: \"",
    "\"# Workflow ID: \"",
    "\"# Task ID: \"",
    "\"# Exact Match word count: \"",
    "\"# Fuzzy Match word count: \"",
    "\"# No Match word count: \"",
    "\"# GlobalSight Instance ID: \"",
    "\"# Edit all: \"",
  };

}
