/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.globalsight.ling.docproc.extractor.cpp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBERCONSTANT = 14;
  /** RegularExpression Id. */
  int CHARACTER = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int ID_OR_KEYWORD = 17;
  /** RegularExpression Id. */
  int CATCHALL = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"/*\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "\"\\n\"",
    "<token of kind 13>",
    "<NUMBERCONSTANT>",
    "<CHARACTER>",
    "<STRING>",
    "<ID_OR_KEYWORD>",
    "<CATCHALL>",
  };

}
