/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.globalsight.ling.docproc.extractor.css;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int L = 2;
  /** RegularExpression Id. */
  int UNICODE_BOM = 3;
  /** RegularExpression Id. */
  int C = 4;
  /** RegularExpression Id. */
  int DIMENSION = 5;
  /** RegularExpression Id. */
  int PERCENTAGE = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int IDENT = 9;
  /** RegularExpression Id. */
  int NMSTART = 10;
  /** RegularExpression Id. */
  int NMCHAR = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int ESCAPE = 13;
  /** RegularExpression Id. */
  int UNICODERANGE = 14;
  /** RegularExpression Id. */
  int HASH = 15;
  /** RegularExpression Id. */
  int FUNCTION = 16;
  /** RegularExpression Id. */
  int URI = 17;
  /** RegularExpression Id. */
  int RGB = 18;
  /** RegularExpression Id. */
  int RECT = 19;
  /** RegularExpression Id. */
  int CHARSET = 20;
  /** RegularExpression Id. */
  int FONTFACE = 21;
  /** RegularExpression Id. */
  int IMPORT = 22;
  /** RegularExpression Id. */
  int MEDIA = 23;
  /** RegularExpression Id. */
  int ATKEYWORD = 24;
  /** RegularExpression Id. */
  int LPAREN = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int LBRACE = 27;
  /** RegularExpression Id. */
  int RBRACE = 28;
  /** RegularExpression Id. */
  int LBRACKET = 29;
  /** RegularExpression Id. */
  int RBRACKET = 30;
  /** RegularExpression Id. */
  int COLON = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int INCLUDES = 33;
  /** RegularExpression Id. */
  int DASHMATCH = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int CDO = 36;
  /** RegularExpression Id. */
  int CDC = 37;
  /** RegularExpression Id. */
  int DELIM = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "<L>",
    "<UNICODE_BOM>",
    "<C>",
    "<DIMENSION>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "<STRING>",
    "<IDENT>",
    "<NMSTART>",
    "<NMCHAR>",
    "<DIGIT>",
    "<ESCAPE>",
    "<UNICODERANGE>",
    "<HASH>",
    "<FUNCTION>",
    "<URI>",
    "<RGB>",
    "<RECT>",
    "\"@charset\"",
    "\"@font-face\"",
    "\"@import\"",
    "\"@media\"",
    "<ATKEYWORD>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\"~=\"",
    "\"|=\"",
    "\",\"",
    "\"<!--\"",
    "<CDC>",
    "<DELIM>",
  };

}
