/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package com.globalsight.ling.docproc.extractor.css;

/** Token Manager. */
public class ParserTokenManager implements ParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1000000000L) != 0L)
            return 21;
         if ((active0 & 0xf00000L) != 0L)
            return 50;
         return -1;
      case 1:
         if ((active0 & 0xf00000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 1;
            return 349;
         }
         if ((active0 & 0x1000000000L) != 0L)
            return 20;
         return -1;
      case 2:
         if ((active0 & 0x1000000000L) != 0L)
            return 12;
         if ((active0 & 0xf00000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
            return 349;
         }
         return -1;
      case 3:
         if ((active0 & 0xf00000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 3;
            return 349;
         }
         if ((active0 & 0x1000000000L) != 0L)
            return 350;
         return -1;
      case 4:
         if ((active0 & 0xf00000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 4;
            return 349;
         }
         return -1;
      case 5:
         if ((active0 & 0x700000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 5;
            return 349;
         }
         if ((active0 & 0x800000L) != 0L)
            return 349;
         return -1;
      case 6:
         if ((active0 & 0x300000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 6;
            return 349;
         }
         if ((active0 & 0x400000L) != 0L)
            return 349;
         return -1;
      case 7:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 7;
            return 349;
         }
         if ((active0 & 0x100000L) != 0L)
            return 349;
         return -1;
      case 8:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 8;
            return 349;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 25);
      case 41:
         return jjStopAtPos(0, 26);
      case 44:
         return jjStopAtPos(0, 35);
      case 58:
         return jjStopAtPos(0, 31);
      case 59:
         return jjStopAtPos(0, 32);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 64:
         return jjMoveStringLiteralDfa1_0(0xf00000L);
      case 91:
         return jjStopAtPos(0, 29);
      case 93:
         return jjStopAtPos(0, 30);
      case 123:
         return jjStopAtPos(0, 27);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 125:
         return jjStopAtPos(0, 28);
      case 126:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      default :
         return jjMoveNfa_0(4, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 61:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 34);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 350);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L);
      case 65:
      case 97:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 349);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 84:
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 349);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L);
      case 84:
      case 116:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 20, 349);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(9, 21, 349);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x0L, 0x8000000000000000L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x0L, 0x4000000000000000L
};
static final long[] jjbitVec2 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec4 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 349;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 349:
               case 51:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 350:
                  if ((0xffffdfffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 18;
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                     jjCheckNAddStates(3, 14);
                  }
                  else if ((0x104001200L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                     jjCheckNAdd(0);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 2)
                        kind = 2;
                     jjCheckNAddTwoStates(1, 3);
                  }
                  else if (curChar == 46)
                     jjCheckNAddStates(15, 17);
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 58;
                  else if (curChar == 35)
                  {
                     if (kind > 15)
                        kind = 15;
                     jjCheckNAddTwoStates(44, 45);
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(18, 20);
                  else if (curChar == 34)
                     jjCheckNAddStates(21, 23);
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 21;
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 5;
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if ((0x104001200L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAdd(0);
                  break;
               case 1:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 2:
                  if (curChar != 10)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 3:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 5:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(6, 7);
                  break;
               case 6:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(6, 7);
                  break;
               case 7:
                  if (curChar == 42)
                     jjCheckNAddStates(24, 26);
                  break;
               case 8:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(9, 7);
                  break;
               case 9:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(9, 7);
                  break;
               case 10:
                  if (curChar == 47 && kind > 4)
                     kind = 4;
                  break;
               case 11:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 12:
                  if (curChar == 45)
                     jjCheckNAddStates(0, 2);
                  break;
               case 13:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 14:
                  if ((0xffffdfffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 15:
                  if (curChar == 45)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if (curChar == 62)
                     jjCheckNAddStates(0, 2);
                  break;
               case 17:
                  if (curChar == 62 && kind > 4)
                     kind = 4;
                  break;
               case 18:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 21:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 34)
                     jjCheckNAddStates(21, 23);
                  break;
               case 24:
                  if ((0xfffffffb00000200L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 25:
                  if (curChar == 34 && kind > 8)
                     kind = 8;
                  break;
               case 27:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 28:
                  if (curChar == 10)
                     jjCheckNAddStates(21, 23);
                  break;
               case 29:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 31);
                  break;
               case 32:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 33:
                  if (curChar == 39)
                     jjCheckNAddStates(18, 20);
                  break;
               case 34:
                  if ((0xffffff7f00000200L & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 35:
                  if (curChar == 39 && kind > 8)
                     kind = 8;
                  break;
               case 37:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 38:
                  if (curChar == 10)
                     jjCheckNAddStates(18, 20);
                  break;
               case 39:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(32, 36);
                  break;
               case 42:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 43:
                  if (curChar != 35)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 44:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 46:
                  if ((0xffffffff00000000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddStates(37, 40);
                  break;
               case 48:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 53:
                  if ((0xffffffff00000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddStates(41, 44);
                  break;
               case 55:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddStates(45, 48);
                  break;
               case 58:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(59, 60);
                  break;
               case 59:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  break;
               case 60:
                  if (curChar == 62 && kind > 37)
                     kind = 37;
                  break;
               case 61:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 62:
                  if (curChar == 46)
                     jjCheckNAddStates(15, 17);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(49, 51);
                  break;
               case 65:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(65, 66);
                  break;
               case 67:
                  if ((0xffffffff00000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(65, 66);
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddStates(52, 55);
                  break;
               case 69:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(65, 66);
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddStates(56, 59);
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 73:
                  if (curChar == 37 && kind > 6)
                     kind = 6;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(74);
                  break;
               case 76:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 78:
                  if ((0xffffffff00000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(60, 63);
                  break;
               case 80:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 81:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(64, 66);
                  break;
               case 83:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(64, 66);
                  break;
               case 84:
                  if (curChar == 40 && kind > 16)
                     kind = 16;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(67, 71);
                  break;
               case 86:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(64, 66);
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(72, 75);
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(76, 80);
                  break;
               case 91:
                  if (curChar == 43)
                     jjCheckNAdd(92);
                  break;
               case 92:
                  if ((0x83ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(92, 93);
                  break;
               case 93:
                  if (curChar == 45)
                     jjCheckNAdd(94);
                  break;
               case 94:
                  if ((0x83ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(94);
                  break;
               case 95:
                  if (curChar == 40)
                     jjCheckNAddStates(81, 88);
                  break;
               case 96:
                  if ((0xfffffc7a00000000L & l) != 0L)
                     jjCheckNAddStates(89, 94);
                  break;
               case 98:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(89, 94);
                  break;
               case 99:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddTwoStates(99, 100);
                  break;
               case 100:
                  if (curChar == 41 && kind > 17)
                     kind = 17;
                  break;
               case 101:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(95, 97);
                  break;
               case 102:
                  if (curChar == 10)
                     jjCheckNAddStates(95, 97);
                  break;
               case 103:
                  if (curChar == 13)
                     jjCheckNAdd(102);
                  break;
               case 104:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(98, 105);
                  break;
               case 105:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(89, 94);
                  break;
               case 106:
                  if (curChar == 39)
                     jjCheckNAddStates(106, 108);
                  break;
               case 107:
                  if ((0xffffff7f00000200L & l) != 0L)
                     jjCheckNAddStates(106, 108);
                  break;
               case 108:
                  if (curChar == 39)
                     jjCheckNAddStates(109, 112);
                  break;
               case 110:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(106, 108);
                  break;
               case 111:
                  if (curChar == 10)
                     jjCheckNAddStates(106, 108);
                  break;
               case 112:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(106, 108);
                  break;
               case 114:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(113, 117);
                  break;
               case 115:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(106, 108);
                  break;
               case 116:
                  if (curChar == 34)
                     jjCheckNAddStates(118, 120);
                  break;
               case 117:
                  if ((0xfffffffb00000200L & l) != 0L)
                     jjCheckNAddStates(118, 120);
                  break;
               case 118:
                  if (curChar == 34)
                     jjCheckNAddStates(109, 112);
                  break;
               case 120:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(118, 120);
                  break;
               case 121:
                  if (curChar == 10)
                     jjCheckNAddStates(118, 120);
                  break;
               case 122:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(118, 120);
                  break;
               case 124:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(121, 125);
                  break;
               case 125:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(118, 120);
                  break;
               case 126:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(126, 135);
                  break;
               case 127:
                  if (curChar == 13)
                     jjCheckNAddTwoStates(128, 102);
                  break;
               case 128:
                  if (curChar == 10)
                     jjCheckNAddStates(136, 143);
                  break;
               case 129:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(144, 152);
                  break;
               case 133:
                  if (curChar == 40)
                     jjCheckNAddStates(153, 157);
                  break;
               case 134:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(158, 160);
                  break;
               case 135:
                  if (curChar == 45)
                     jjCheckNAdd(136);
                  break;
               case 136:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(161, 166);
                  break;
               case 137:
                  if (curChar == 37)
                     jjCheckNAddStates(167, 170);
                  break;
               case 138:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddTwoStates(138, 139);
                  break;
               case 139:
                  if (curChar == 44)
                     jjCheckNAddStates(171, 175);
                  break;
               case 140:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(176, 178);
                  break;
               case 141:
                  if (curChar == 45)
                     jjCheckNAdd(142);
                  break;
               case 142:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(179, 184);
                  break;
               case 143:
                  if (curChar == 37)
                     jjCheckNAddStates(185, 188);
                  break;
               case 144:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddTwoStates(144, 145);
                  break;
               case 145:
                  if (curChar == 44)
                     jjCheckNAddStates(189, 193);
                  break;
               case 146:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 147:
                  if (curChar == 45)
                     jjCheckNAdd(148);
                  break;
               case 148:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(197, 202);
                  break;
               case 149:
                  if (curChar == 37)
                     jjCheckNAddStates(203, 206);
                  break;
               case 150:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddTwoStates(150, 151);
                  break;
               case 151:
                  if (curChar == 41 && kind > 18)
                     kind = 18;
                  break;
               case 152:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(207, 209);
                  break;
               case 153:
                  if (curChar == 10)
                     jjCheckNAddStates(207, 209);
                  break;
               case 154:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(210, 213);
                  break;
               case 156:
                  if (curChar == 10)
                     jjCheckNAddStates(210, 213);
                  break;
               case 157:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(214, 216);
                  break;
               case 159:
                  if (curChar == 10)
                     jjCheckNAddStates(214, 216);
                  break;
               case 160:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(217, 220);
                  break;
               case 162:
                  if (curChar == 10)
                     jjCheckNAddStates(217, 220);
                  break;
               case 163:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(221, 223);
                  break;
               case 165:
                  if (curChar == 10)
                     jjCheckNAddStates(221, 223);
                  break;
               case 166:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(224, 227);
                  break;
               case 168:
                  if (curChar == 10)
                     jjCheckNAddStates(224, 227);
                  break;
               case 169:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 172:
                  if (curChar == 40)
                     jjCheckNAddStates(228, 234);
                  break;
               case 173:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(235, 239);
                  break;
               case 174:
                  if (curChar == 45)
                     jjCheckNAddStates(240, 242);
                  break;
               case 175:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 176:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(243, 253);
                  break;
               case 177:
                  if (curChar == 37)
                     jjCheckNAddStates(254, 261);
                  break;
               case 178:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(262, 267);
                  break;
               case 179:
                  if (curChar == 44)
                     jjCheckNAddStates(268, 274);
                  break;
               case 180:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(275, 279);
                  break;
               case 181:
                  if (curChar == 45)
                     jjCheckNAddStates(280, 282);
                  break;
               case 182:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 183:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(283, 293);
                  break;
               case 184:
                  if (curChar == 37)
                     jjCheckNAddStates(294, 301);
                  break;
               case 185:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(302, 307);
                  break;
               case 186:
                  if (curChar == 44)
                     jjCheckNAddStates(308, 314);
                  break;
               case 187:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(315, 319);
                  break;
               case 188:
                  if (curChar == 45)
                     jjCheckNAddStates(320, 322);
                  break;
               case 189:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 190:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(323, 333);
                  break;
               case 191:
                  if (curChar == 37)
                     jjCheckNAddStates(334, 341);
                  break;
               case 192:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(342, 347);
                  break;
               case 193:
                  if (curChar == 44)
                     jjCheckNAddStates(348, 354);
                  break;
               case 194:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddStates(355, 359);
                  break;
               case 195:
                  if (curChar == 45)
                     jjCheckNAddStates(360, 362);
                  break;
               case 196:
                  if (curChar == 46)
                     jjCheckNAdd(197);
                  break;
               case 197:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(363, 370);
                  break;
               case 198:
                  if (curChar == 37)
                     jjCheckNAddStates(371, 374);
                  break;
               case 199:
                  if ((0x104001200L & l) != 0L)
                     jjCheckNAddTwoStates(199, 200);
                  break;
               case 200:
                  if (curChar == 41 && kind > 19)
                     kind = 19;
                  break;
               case 201:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(375, 377);
                  break;
               case 202:
                  if (curChar == 10)
                     jjCheckNAddStates(375, 377);
                  break;
               case 203:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 39)
                     jjCheckNAddStates(378, 380);
                  break;
               case 205:
                  if ((0xffffff7f00000200L & l) != 0L)
                     jjCheckNAddStates(378, 380);
                  break;
               case 206:
                  if (curChar == 39)
                     jjCheckNAddStates(371, 374);
                  break;
               case 208:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(378, 380);
                  break;
               case 209:
                  if (curChar == 10)
                     jjCheckNAddStates(378, 380);
                  break;
               case 210:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(378, 380);
                  break;
               case 212:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(381, 385);
                  break;
               case 213:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(378, 380);
                  break;
               case 214:
                  if (curChar == 34)
                     jjCheckNAddStates(386, 388);
                  break;
               case 215:
                  if ((0xfffffffb00000200L & l) != 0L)
                     jjCheckNAddStates(386, 388);
                  break;
               case 216:
                  if (curChar == 34)
                     jjCheckNAddStates(371, 374);
                  break;
               case 218:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(386, 388);
                  break;
               case 219:
                  if (curChar == 10)
                     jjCheckNAddStates(386, 388);
                  break;
               case 220:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(386, 388);
                  break;
               case 222:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(389, 393);
                  break;
               case 223:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(386, 388);
                  break;
               case 228:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(394, 403);
                  break;
               case 229:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(404, 411);
                  break;
               case 230:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(230, 196);
                  break;
               case 231:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(412, 417);
                  break;
               case 232:
                  if (curChar == 10)
                     jjCheckNAddStates(412, 417);
                  break;
               case 233:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(418, 424);
                  break;
               case 235:
                  if (curChar == 10)
                     jjCheckNAddStates(418, 424);
                  break;
               case 236:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 39)
                     jjCheckNAddStates(425, 427);
                  break;
               case 238:
                  if ((0xffffff7f00000200L & l) != 0L)
                     jjCheckNAddStates(425, 427);
                  break;
               case 239:
                  if (curChar == 39)
                     jjCheckNAddStates(334, 341);
                  break;
               case 241:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(425, 427);
                  break;
               case 242:
                  if (curChar == 10)
                     jjCheckNAddStates(425, 427);
                  break;
               case 243:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(425, 427);
                  break;
               case 245:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(428, 432);
                  break;
               case 246:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(425, 427);
                  break;
               case 247:
                  if (curChar == 34)
                     jjCheckNAddStates(433, 435);
                  break;
               case 248:
                  if ((0xfffffffb00000200L & l) != 0L)
                     jjCheckNAddStates(433, 435);
                  break;
               case 249:
                  if (curChar == 34)
                     jjCheckNAddStates(334, 341);
                  break;
               case 251:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(433, 435);
                  break;
               case 252:
                  if (curChar == 10)
                     jjCheckNAddStates(433, 435);
                  break;
               case 253:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(433, 435);
                  break;
               case 255:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(436, 440);
                  break;
               case 256:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(433, 435);
                  break;
               case 257:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(441, 460);
                  break;
               case 262:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(461, 473);
                  break;
               case 263:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(263, 189);
                  break;
               case 264:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(474, 493);
                  break;
               case 265:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(494, 499);
                  break;
               case 266:
                  if (curChar == 10)
                     jjCheckNAddStates(494, 499);
                  break;
               case 267:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(500, 506);
                  break;
               case 269:
                  if (curChar == 10)
                     jjCheckNAddStates(500, 506);
                  break;
               case 270:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 39)
                     jjCheckNAddStates(507, 509);
                  break;
               case 272:
                  if ((0xffffff7f00000200L & l) != 0L)
                     jjCheckNAddStates(507, 509);
                  break;
               case 273:
                  if (curChar == 39)
                     jjCheckNAddStates(294, 301);
                  break;
               case 275:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(507, 509);
                  break;
               case 276:
                  if (curChar == 10)
                     jjCheckNAddStates(507, 509);
                  break;
               case 277:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(507, 509);
                  break;
               case 279:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(510, 514);
                  break;
               case 280:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(507, 509);
                  break;
               case 281:
                  if (curChar == 34)
                     jjCheckNAddStates(515, 517);
                  break;
               case 282:
                  if ((0xfffffffb00000200L & l) != 0L)
                     jjCheckNAddStates(515, 517);
                  break;
               case 283:
                  if (curChar == 34)
                     jjCheckNAddStates(294, 301);
                  break;
               case 285:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(515, 517);
                  break;
               case 286:
                  if (curChar == 10)
                     jjCheckNAddStates(515, 517);
                  break;
               case 287:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(515, 517);
                  break;
               case 289:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(518, 522);
                  break;
               case 290:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(515, 517);
                  break;
               case 291:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(523, 545);
                  break;
               case 296:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(546, 558);
                  break;
               case 297:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(297, 182);
                  break;
               case 298:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(559, 581);
                  break;
               case 299:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(582, 587);
                  break;
               case 300:
                  if (curChar == 10)
                     jjCheckNAddStates(582, 587);
                  break;
               case 301:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 302:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(588, 594);
                  break;
               case 303:
                  if (curChar == 10)
                     jjCheckNAddStates(588, 594);
                  break;
               case 304:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 39)
                     jjCheckNAddStates(595, 597);
                  break;
               case 306:
                  if ((0xffffff7f00000200L & l) != 0L)
                     jjCheckNAddStates(595, 597);
                  break;
               case 307:
                  if (curChar == 39)
                     jjCheckNAddStates(254, 261);
                  break;
               case 309:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(595, 597);
                  break;
               case 310:
                  if (curChar == 10)
                     jjCheckNAddStates(595, 597);
                  break;
               case 311:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 312:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(595, 597);
                  break;
               case 313:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(598, 602);
                  break;
               case 314:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(595, 597);
                  break;
               case 315:
                  if (curChar == 34)
                     jjCheckNAddStates(603, 605);
                  break;
               case 316:
                  if ((0xfffffffb00000200L & l) != 0L)
                     jjCheckNAddStates(603, 605);
                  break;
               case 317:
                  if (curChar == 34)
                     jjCheckNAddStates(254, 261);
                  break;
               case 319:
                  if ((0x3400L & l) != 0L)
                     jjCheckNAddStates(603, 605);
                  break;
               case 320:
                  if (curChar == 10)
                     jjCheckNAddStates(603, 605);
                  break;
               case 321:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 320;
                  break;
               case 322:
                  if ((0xffffffff00000000L & l) != 0L)
                     jjCheckNAddStates(603, 605);
                  break;
               case 323:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(606, 610);
                  break;
               case 324:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(603, 605);
                  break;
               case 325:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(611, 633);
                  break;
               case 330:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(634, 646);
                  break;
               case 331:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(331, 175);
                  break;
               case 332:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(647, 669);
                  break;
               case 333:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAddStates(670, 675);
                  break;
               case 334:
                  if (curChar == 10)
                     jjCheckNAddStates(670, 675);
                  break;
               case 335:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 339:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAddStates(3, 14);
                  break;
               case 340:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(676, 678);
                  break;
               case 341:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(341, 342);
                  break;
               case 342:
                  if (curChar == 46)
                     jjCheckNAdd(63);
                  break;
               case 343:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(343, 73);
                  break;
               case 344:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(344, 345);
                  break;
               case 345:
                  if (curChar == 46)
                     jjCheckNAdd(72);
                  break;
               case 346:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(346);
                  break;
               case 347:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(347, 348);
                  break;
               case 348:
                  if (curChar == 46)
                     jjCheckNAdd(74);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 349:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 24)
                        kind = 24;
                     jjCheckNAddTwoStates(51, 52);
                  }
                  else if (curChar == 92)
                     jjCheckNAddTwoStates(53, 54);
                  break;
               case 350:
                  jjAddStates(679, 680);
                  jjCheckNAddStates(0, 2);
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(681, 685);
                  }
                  else if (curChar == 92)
                     jjCheckNAddStates(686, 689);
                  else if (curChar == 64)
                     jjAddStates(690, 691);
                  if ((0x4000000040000L & l) != 0L)
                     jjAddStates(692, 693);
                  else if ((0x20000000200000L & l) != 0L)
                     jjAddStates(694, 695);
                  break;
               case 50:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 24)
                        kind = 24;
                     jjCheckNAddTwoStates(51, 52);
                  }
                  else if (curChar == 92)
                     jjCheckNAddTwoStates(53, 57);
                  break;
               case 6:
                  jjCheckNAddTwoStates(6, 7);
                  break;
               case 8:
               case 9:
                  jjCheckNAddTwoStates(9, 7);
                  break;
               case 13:
                  jjCheckNAddStates(0, 2);
                  break;
               case 14:
                  jjAddStates(679, 680);
                  break;
               case 24:
               case 30:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(21, 23);
                  break;
               case 26:
                  if (curChar == 92)
                     jjCheckNAddStates(696, 699);
                  break;
               case 31:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(27, 31);
                  break;
               case 34:
               case 40:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 36:
                  if (curChar == 92)
                     jjCheckNAddStates(700, 703);
                  break;
               case 41:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(32, 36);
                  break;
               case 44:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 45:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 46:
                  if ((0x7fffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 47:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddStates(37, 40);
                  break;
               case 49:
                  if (curChar == 64)
                     jjAddStates(690, 691);
                  break;
               case 51:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 52:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(53, 54);
                  break;
               case 53:
                  if ((0x7fffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 54:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddStates(41, 44);
                  break;
               case 56:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(53, 57);
                  break;
               case 57:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddStates(45, 48);
                  break;
               case 64:
               case 65:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(65, 66);
                  break;
               case 66:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(67, 68);
                  break;
               case 67:
                  if ((0x7fffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(65, 66);
                  break;
               case 68:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddStates(52, 55);
                  break;
               case 70:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(67, 71);
                  break;
               case 71:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddStates(56, 59);
                  break;
               case 75:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(681, 685);
                  break;
               case 76:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 77:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 78:
                  if ((0x7fffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 79:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(60, 63);
                  break;
               case 81:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(64, 66);
                  break;
               case 82:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(83, 85);
                  break;
               case 83:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(64, 66);
                  break;
               case 85:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(67, 71);
                  break;
               case 87:
                  if (curChar == 92)
                     jjCheckNAddStates(686, 689);
                  break;
               case 88:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(72, 75);
                  break;
               case 89:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(76, 80);
                  break;
               case 90:
                  if ((0x20000000200000L & l) != 0L)
                     jjAddStates(694, 695);
                  break;
               case 92:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjAddStates(704, 705);
                  break;
               case 94:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
               case 98:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(89, 94);
                  break;
               case 97:
                  if (curChar == 92)
                     jjCheckNAddTwoStates(98, 104);
                  break;
               case 104:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(98, 105);
                  break;
               case 107:
               case 113:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(106, 108);
                  break;
               case 109:
                  if (curChar == 92)
                     jjCheckNAddStates(706, 709);
                  break;
               case 114:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(113, 117);
                  break;
               case 117:
               case 123:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(118, 120);
                  break;
               case 119:
                  if (curChar == 92)
                     jjCheckNAddStates(710, 713);
                  break;
               case 124:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(121, 125);
                  break;
               case 130:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 131:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if ((0x4000000040000L & l) != 0L)
                     jjAddStates(692, 693);
                  break;
               case 170:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 171:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 205:
               case 211:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(378, 380);
                  break;
               case 207:
                  if (curChar == 92)
                     jjCheckNAddStates(714, 717);
                  break;
               case 212:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(381, 385);
                  break;
               case 215:
               case 221:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(386, 388);
                  break;
               case 217:
                  if (curChar == 92)
                     jjCheckNAddStates(718, 721);
                  break;
               case 222:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(389, 393);
                  break;
               case 224:
                  if ((0x800000008000L & l) != 0L)
                     jjAddStates(371, 374);
                  break;
               case 225:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 238:
               case 244:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(425, 427);
                  break;
               case 240:
                  if (curChar == 92)
                     jjCheckNAddStates(722, 725);
                  break;
               case 245:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(428, 432);
                  break;
               case 248:
               case 254:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(433, 435);
                  break;
               case 250:
                  if (curChar == 92)
                     jjCheckNAddStates(726, 729);
                  break;
               case 255:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(436, 440);
                  break;
               case 258:
                  if ((0x800000008000L & l) != 0L)
                     jjAddStates(334, 341);
                  break;
               case 259:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 272:
               case 278:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(507, 509);
                  break;
               case 274:
                  if (curChar == 92)
                     jjCheckNAddStates(730, 733);
                  break;
               case 279:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(510, 514);
                  break;
               case 282:
               case 288:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(515, 517);
                  break;
               case 284:
                  if (curChar == 92)
                     jjCheckNAddStates(734, 737);
                  break;
               case 289:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(518, 522);
                  break;
               case 292:
                  if ((0x800000008000L & l) != 0L)
                     jjAddStates(294, 301);
                  break;
               case 293:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 294:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 295:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 306:
               case 312:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(595, 597);
                  break;
               case 308:
                  if (curChar == 92)
                     jjCheckNAddStates(738, 741);
                  break;
               case 313:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(598, 602);
                  break;
               case 316:
               case 322:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(603, 605);
                  break;
               case 318:
                  if (curChar == 92)
                     jjCheckNAddStates(742, 745);
                  break;
               case 323:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(606, 610);
                  break;
               case 326:
                  if ((0x800000008000L & l) != 0L)
                     jjAddStates(254, 261);
                  break;
               case 327:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 328:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 327;
                  break;
               case 329:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 328;
                  break;
               case 336:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 337:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 338:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 337;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 349:
               case 51:
               case 53:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 350:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 2);
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(679, 680);
                  break;
               case 4:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 3)
                        kind = 3;
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(681, 685);
                  }
                  break;
               case 50:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 6:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(6, 7);
                  break;
               case 8:
               case 9:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(9, 7);
                  break;
               case 13:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 2);
                  break;
               case 14:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(679, 680);
                  break;
               case 24:
               case 30:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(21, 23);
                  break;
               case 34:
               case 40:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(18, 20);
                  break;
               case 44:
               case 46:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 64:
               case 65:
               case 67:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(65, 66);
                  break;
               case 75:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(681, 685);
                  break;
               case 76:
               case 78:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 81:
               case 83:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(64, 66);
                  break;
               case 96:
               case 98:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(89, 94);
                  break;
               case 107:
               case 113:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(106, 108);
                  break;
               case 117:
               case 123:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(118, 120);
                  break;
               case 205:
               case 211:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(378, 380);
                  break;
               case 215:
               case 221:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(386, 388);
                  break;
               case 238:
               case 244:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(425, 427);
                  break;
               case 248:
               case 254:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(433, 435);
                  break;
               case 272:
               case 278:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(507, 509);
                  break;
               case 282:
               case 288:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(515, 517);
                  break;
               case 306:
               case 312:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(595, 597);
                  break;
               case 316:
               case 322:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(603, 605);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 349 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   13, 14, 19, 340, 341, 342, 64, 70, 343, 344, 345, 73, 346, 347, 348, 63, 
   72, 74, 34, 35, 36, 24, 25, 26, 7, 8, 10, 24, 31, 32, 25, 26, 
   34, 41, 42, 35, 36, 44, 45, 47, 48, 51, 52, 54, 55, 57, 55, 51, 
   52, 63, 64, 70, 65, 66, 68, 69, 71, 69, 65, 66, 76, 77, 79, 80, 
   81, 82, 84, 81, 82, 85, 86, 84, 88, 80, 76, 77, 89, 86, 81, 82, 
   84, 96, 97, 106, 116, 100, 126, 127, 129, 96, 97, 99, 101, 103, 100, 101, 
   103, 100, 96, 97, 104, 105, 99, 101, 103, 100, 107, 108, 109, 99, 101, 103, 
   100, 107, 114, 115, 108, 109, 117, 118, 119, 117, 124, 125, 118, 119, 96, 97, 
   106, 116, 99, 101, 103, 100, 126, 127, 96, 97, 106, 116, 99, 100, 126, 127, 
   96, 97, 106, 116, 99, 101, 103, 100, 129, 134, 167, 169, 135, 136, 134, 135, 
   136, 136, 137, 138, 164, 166, 139, 138, 164, 166, 139, 140, 161, 163, 141, 142, 
   140, 141, 142, 142, 143, 144, 158, 160, 145, 144, 158, 160, 145, 146, 155, 157, 
   147, 148, 146, 147, 148, 148, 149, 150, 152, 154, 151, 150, 152, 154, 151, 152, 
   154, 151, 155, 157, 147, 148, 158, 160, 145, 161, 163, 141, 142, 164, 166, 139, 
   167, 169, 135, 136, 173, 333, 335, 174, 175, 329, 330, 173, 174, 175, 329, 330, 
   175, 329, 330, 177, 305, 315, 178, 302, 304, 179, 181, 182, 295, 325, 178, 302, 
   304, 179, 181, 182, 295, 296, 178, 179, 181, 182, 295, 296, 180, 299, 301, 181, 
   182, 295, 296, 180, 181, 182, 295, 296, 182, 295, 296, 184, 271, 281, 185, 268, 
   270, 186, 188, 189, 261, 291, 185, 268, 270, 186, 188, 189, 261, 262, 185, 186, 
   188, 189, 261, 262, 187, 265, 267, 188, 189, 261, 262, 187, 188, 189, 261, 262, 
   189, 261, 262, 191, 237, 247, 192, 234, 236, 193, 195, 196, 227, 257, 192, 234, 
   236, 193, 195, 196, 227, 228, 192, 193, 195, 196, 227, 228, 194, 231, 233, 195, 
   196, 227, 228, 194, 195, 196, 227, 228, 196, 227, 228, 197, 198, 204, 214, 199, 
   201, 203, 200, 199, 201, 203, 200, 201, 203, 200, 205, 206, 207, 205, 212, 213, 
   206, 207, 215, 216, 217, 215, 222, 223, 216, 217, 229, 230, 196, 198, 204, 214, 
   199, 201, 203, 200, 229, 198, 204, 214, 199, 201, 203, 200, 231, 233, 195, 196, 
   227, 228, 234, 236, 193, 195, 196, 227, 228, 238, 239, 240, 238, 245, 246, 239, 
   240, 248, 249, 250, 248, 255, 256, 249, 250, 191, 237, 247, 192, 234, 236, 193, 
   195, 229, 230, 196, 198, 204, 214, 227, 199, 201, 203, 200, 257, 263, 189, 191, 
   237, 247, 192, 234, 236, 193, 195, 196, 227, 264, 191, 237, 247, 192, 234, 236, 
   193, 195, 229, 230, 196, 198, 204, 214, 227, 199, 201, 203, 200, 264, 265, 267, 
   188, 189, 261, 262, 268, 270, 186, 188, 189, 261, 262, 272, 273, 274, 272, 279, 
   280, 273, 274, 282, 283, 284, 282, 289, 290, 283, 284, 184, 271, 281, 185, 268, 
   270, 186, 188, 263, 189, 191, 237, 247, 261, 192, 234, 236, 193, 195, 196, 227, 
   264, 291, 297, 182, 184, 271, 281, 185, 268, 270, 186, 188, 189, 261, 298, 184, 
   271, 281, 185, 268, 270, 186, 188, 263, 189, 191, 237, 247, 261, 192, 234, 236, 
   193, 195, 196, 227, 264, 298, 299, 301, 181, 182, 295, 296, 302, 304, 179, 181, 
   182, 295, 296, 306, 307, 308, 306, 313, 314, 307, 308, 316, 317, 318, 316, 323, 
   324, 317, 318, 177, 305, 315, 178, 302, 304, 179, 181, 297, 182, 184, 271, 281, 
   295, 185, 268, 270, 186, 188, 189, 261, 298, 325, 331, 175, 177, 305, 315, 178, 
   302, 304, 179, 181, 182, 295, 332, 177, 305, 315, 178, 302, 304, 179, 181, 297, 
   182, 184, 271, 281, 295, 185, 268, 270, 186, 188, 189, 261, 298, 332, 333, 335, 
   174, 175, 329, 330, 340, 64, 70, 15, 16, 76, 77, 81, 82, 84, 78, 88, 
   83, 89, 50, 56, 171, 338, 91, 131, 27, 29, 30, 31, 37, 39, 40, 41, 
   92, 93, 110, 112, 113, 114, 120, 122, 123, 124, 208, 210, 211, 212, 218, 220, 
   221, 222, 241, 243, 244, 245, 251, 253, 254, 255, 275, 277, 278, 279, 285, 287, 
   288, 289, 309, 311, 312, 313, 319, 321, 322, 323, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 254:
         return ((jjbitVec0[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec1[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec4[i2] & l2) != 0L);
      default :
         if ((jjbitVec2[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\50", 
"\51", "\173", "\175", "\133", "\135", "\72", "\73", "\176\75", "\174\75", "\54", 
"\74\41\55\55", null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[349];
private final int[] jjstateSet = new int[698];
protected char curChar;
/** Constructor. */
public ParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 349; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 38)
   {
      jjmatchedKind = 38;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
